"""Initial migration with Tags system

Revision ID: 9cf6cb2bb486
Revises: 
Create Date: 2026-05-06 20:12:13.138012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf6cb2bb486'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('content_type', sa.String(), nullable=False))
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.drop_column('tg_file_id')

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_pushed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('content_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('tags')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.alter_column('content_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('last_pushed_at')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tg_file_id', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.drop_column('content_type')
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###
